---
#file: roles/firewall/tasks/handlers/main.yml

    - name: restart ip6tables
      service: name=ip6tables state=restarted
      ignore_errors: yes
      when: (ansible_os_family=="RedHat" and ansible_distribution_major_version=="6")
      
    - name: reload firewalld
      command: firewall-cmd --reload
      ignore_errors: yes
      when: (ansible_os_family=="RedHat" and ansible_distribution_major_version=="7")
